name: zeal_docs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 */7 * *"
  push:
    branches:
      - main


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          pip install requests
          python Run.py

      - name: Set variables
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash
  
         # 添加commit 防止workflows停止
      - name: push rep
        run: |
          echo ${{ env.BUILDTIME }} >> commit
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "triggle by commit ${{ env.BUILDTIME }}"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin main

      - name: Upload to Releases
        uses: ncipollo/release-action@main
        if: ${{ steps.upload.outputs.status }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.timestamp.outputs.current_time }}
          artifacts: docs/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}